name: Snake Game

on:
  # run automatically every 5 hours
  schedule:
    - cron: "0 */5 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: DmitryGityuk
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
          
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
